# Generated by Django 5.2 on 2025-05-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador')], max_length=20),
        ),
    ]
